ifast:
  projectName: ifast
  projectRootURL: http://127.0.0.1:${server.port}/
  demoMode: false
  devMode: true
  tempDir: /Users/Aron/dev_projects/idea/ifast/temp/
  jwt:
    userPrimaryKey: userId
    expireTokenKeyPrefix: ifast:expireToken
    expireTime: 7200000
    refreshTokenExpire: 604800000
  swagger:
    title: ifast接口文档
    description: 开发人员太懒，没有写描述
    contactName: Aron
    contactEmail: izenglong@163.com
    contactUrl: http://ifast.site/doc.html
    basePackage: com.ifast
    termsOfServiceUrl: ${ifast.projectRootURL}doc.html
  shiro:
    jsessionidKey: SESSION
    sessionKeyPrefix: ${ifast.projectName}:session
  oss:
    aliyun: # 配置 accessKeySecret 启用阿里云OSS
      accessKeyId: LTAI4G5fwdUktnS4Q2xUcfmT
      accessKeySecret: 1gN5Ff72JECUj8o6xAyntqPmdrCkl3
      bucketName: nkzj
      # endpoint以深圳为例，其它region请按实际情况填写
      endpoint: http://oss-cn-shenzhen.aliyuncs.com
  sms:
    cacheKey: ${ifast.projectName}:cache
    cacheKeyPrefix: sms
    codeExpireTime: 900000
    scenes: # 短信内容清单
      validCode: 验证码{code}，您正在进行身份验证，打死也不要告诉别人哦！
    zt: # 配置 uname 启用上海助通短信平台
      uname: UNAME
      passwd: PASSWD
      productId: PRODUCT_ID
    # 配置accessKeyId和accessKeySecret，添加配置表项sys_config.sms_aliyun_validCode
    aliyun: # 配置 accessKeySecret 启用上海助通短信平台
      accessKeyId:
      accessKeySecret:
      scenes:
        # 配置格式为包含SignName和TemplateCode的json字符串：sys_config.sms_aliyun_validCode = {SignName, TemplateCode}
        validCode: sms_aliyun_validCode
spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        master:
          url: jdbc:mysql://47.115.200.228:3306/testenvironment?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&useSSL=false #172.20.11.23
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
        slave_1:
          url: jdbc:mysql://47.115.200.228:3306/testenvironment?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&useSSL=false
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver

#邮件配置
  mail:
    #smtp服务主机
    host: smtp.sina.com
    port: 465
    #服务协议
    protocol: smtps
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: builddsjj2021@sina.com
    #授权码
    password: 688faeeebeabb28c
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
